# Control file for continuous integration testing at http://travis-ci.org/

language: c

matrix:
  include:
    - os: linux
      compiler: clang
    - os: linux
      compiler: gcc
    # An unoptimised C99 build, for detecting non-static inline functions
    - os: linux
      compiler: gcc
      env: CFLAGS="-std=gnu99 -O0"
    - os: osx
      compiler: clang

env:
  global:
    - HTSDIR=./htslib

# For linux systems
addons:
  apt:
    packages:
    - liblzma-dev
    - libbz2-dev

# For MacOSX systems
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then HOMEBREW_NO_AUTO_UPDATE=1 brew install xz || ( brew update && brew install xz ); fi

before_script:
  # Clone samtools/htslib (or another repository, as specified by a Travis CI
  # repository $HTSREPO setting) and check out a corresponding branch with the
  # same name, if any, or otherwise the default branch.
  - .travis/clone ${HTSREPO:-https://github.com/mchristiansen23/htslib.git} $HTSDIR $TRAVIS_BRANCH

script: make -e && make -e test && make package
